name: Vercel Preview Deployment for Node.js App

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Run tests to validate code
      - name: Run Tests
        run: npm test

      # Step 5: Build project artifacts
      - name: Build Project
        run: |
          npm run build
          mkdir -p .vercel/output
          cp -r dist/* .vercel/output/

      # Step 6: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel

      # Step 7: Pull Vercel environment configuration
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Step 8: Deploy prebuilt project artifacts
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
