name: Vercel Preview Deployment for Node.js App

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Run application tests
      - name: Run Tests
        run: npm run test

  Deploy-Preview:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel

      # Step 3: Pull Vercel environment configuration
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Step 4: Build project artifacts
      - name: Build Project Artifacts
        run: vercel build --output=.vercel/output --token=${{ secrets.VERCEL_TOKEN }}

      # Step 5: Deploy prebuilt project artifacts
      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
